python main.py --batch_size 16 --model_name "Pythia14m" --data "tinystories"
pythia main.py --batch_size 16 --model_name "Pythia70m" --data "tinystories"
pythia main.py --batch_size 16 --model_name "Pythia160m" --data "tinystories"
pythia main.py --batch_size 16 --model_name "Pythia410m" --data "tinystories"
pythia main.py --batch_size 16 --model_name "Pythia1b" --data "tinystories"
pythia main.py --batch_size 16 --model_name "Pythia1.4b" --data "tinystories"
pythia main.py --batch_size 16 --model_name "Pythia2.8b" --data "tinystories"
pythia main.py --batch_size 16 --model_name "Pythia6.9b" --data "tinystories"
pythia main.py --batch_size 16 --model_name "Pythia12b" --data "tinystories"


python main.py --batch_size 16 --model_name "Pythia14m" --data "alpaca"
pythia main.py --batch_size 16 --model_name "Pythia70m" --data "alpaca"
pythia main.py --batch_size 16 --model_name "Pythia160m" --data "alpaca"
pythia main.py --batch_size 16 --model_name "Pythia410m" --data "alpaca"
pythia main.py --batch_size 16 --model_name "Pythia1b" --data "alpaca"
pythia main.py --batch_size 16 --model_name "Pythia1.4b" --data "alpaca"
pythia main.py --batch_size 16 --model_name "Pythia2.8b" --data "alpaca"
pythia main.py --batch_size 16 --model_name "Pythia6.9b" --data "alpaca"
pythia main.py --batch_size 16 --model_name "Pythia12b" --data "alpaca"


python main.py --batch_size 16 --model_name "Pythia14m" --data "summarisation"
pythia main.py --batch_size 16 --model_name "Pythia70m" --data "summarisation"
pythia main.py --batch_size 16 --model_name "Pythia160m" --data "summarisation"
pythia main.py --batch_size 16 --model_name "Pythia410m" --data "summarisation"
pythia main.py --batch_size 16 --model_name "Pythia1b" --data "summarisation"
pythia main.py --batch_size 16 --model_name "Pythia1.4b" --data "summarisation"
pythia main.py --batch_size 16 --model_name "Pythia2.8b" --data "summarisation"
pythia main.py --batch_size 16 --model_name "Pythia6.9b" --data "summarisation"
pythia main.py --batch_size 16 --model_name "Pythia12b" --data "summarisation"
