python main.py --batch_size 16 --model_name "Pythia14m" --data "tinystories" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia70m" --data "tinystories" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia160m" --data "tinystories" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia410m" --data "tinystories" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia1b" --data "tinystories" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia1.4b" --data "tinystories" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia2.8b" --data "tinystories" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia6.9b" --data "tinystories" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia12b" --data "tinystories" --device "mps"


python main.py --batch_size 16 --model_name "Pythia14m" --data "alpaca" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia70m" --data "alpaca" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia160m" --data "alpaca" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia410m" --data "alpaca" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia1b" --data "alpaca" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia1.4b" --data "alpaca" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia2.8b" --data "alpaca" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia6.9b" --data "alpaca" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia12b" --data "alpaca" --device "mps"


python main.py --batch_size 16 --model_name "Pythia14m" --data "summarisation" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia70m" --data "summarisation" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia160m" --data "summarisation" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia410m" --data "summarisation" --device "mps" 
pythia main.py --batch_size 16 --model_name "Pythia1b" --data "summarisation" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia1.4b" --data "summarisation" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia2.8b" --data "summarisation" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia6.9b" --data "summarisation" --device "mps"
pythia main.py --batch_size 16 --model_name "Pythia12b" --data "summarisation" --device "mps"
